menu:
  title: "&8&lEncantamientos"
  enchants:
    SHARPNESS:
      name: "&aSharpness"
      price: 1000
      multiplier: 2
      max: 8
      lore:
        - "&7A powerful enchantment"
        - "&7that increases damage."
    PROTECTION:
      name: "&bProtection"
      price: 1200
      multiplier: 2.5
      max: 4
      lore:
        - "&7Reduces incoming damage."
